version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17.6
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node-{{ checksum "package.json" }}
      - run:
          name: Install serverless plugins
          command: |
            serverless plugin install --name serverless-plugin-aws-alerts
            serverless plugin install --nameserverless-plugin-canary-deployments
      - run:
          name: Deploy application
          environment:
            SLS_DEBUG: '*'
          command: |
            sls deploy -v

workflows:
  sample:
    jobs:
      - build
